Hw 2
================
Amanda Kramer
9/30/20

## Problem 1

First I will read and clean the Mr. Trash Wheel sheet:

  - specify the sheet in the Excel file and to omit non-data entries
    (rows with notes / figures; columns containing notes) using
    arguments in read\_excel
  - use reasonable variable names
  - omit rows that do not include dumpster-specific data
  - round the number of sports balls to the nearest integer and converts
    the result to an integer variable (using as.integer)

<!-- end list -->

``` r
trash_wheel = 
  read_excel("./subd/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = 1, skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  select(-x15, -x16, -x17) %>% 
  mutate(sports_balls = as.integer(sports_balls))
```

    ## New names:
    ## * `` -> ...15
    ## * `` -> ...16
    ## * `` -> ...17

Next I will read and clean precipitation data for 2017 and 2018. For
each omit rows without precipitation data and add a variable year. Next,
combine precipitation datasets and convert month to a character variable
(the variable month.name is built into R and should be useful).

``` r
precip_17 = 
  read_excel("./subd/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = 6, skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year = 2017) %>% 
  select(year, month, total)

precip_18 = 
  read_excel("./subd/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = 5, skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year = 2018) %>% 
  select(year, month, total)

precip_all = 
  full_join(precip_17, precip_18) %>% 
  mutate(month = month.name[month])
```

    ## Joining, by = c("year", "month", "total")

My trash\_wheel data set has 344 observations, and my precip\_all data
set has 24 observations. Trash\_wheel includes variables to show the
number of items removed from the harbor, such as `glass_bottles` and
`grocery_bags`. We can also see that the median number of `sports_balls`
in the dumpster in 2017 was 8. The precip\_all dataframe can show us
that the total precipitation in 2018 was 70.33 inches.

## Problem 2

First, read and clean the data; retain line, station, name, station
latitude / longitude, routes served, entry, vending, entrance type, and
ADA compliance. Convert the entry variable from character (YES vs NO) to
a logical variable (the ifelse or recode function may be useful).

``` r
nyc_subway =
  read_csv("./subd/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>%
select(line:entry, vending, ada) %>%
   mutate(entry = recode(entry, YES = "TRUE", NO = "FALSE"))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

My nyc\_subway data set has 1868 and 19observations. The dataset
contains line, station\_name, station\_latitude, station\_longitude,
route1, route2, route3, route4, route5, route6, route7, route8, route9,
route10, route11, entrance\_type, entry, vending, ada Thus far to clean
the data, we’ve cleaned up the names, removed unneeded variables, and
changed the file type of “entry”. These data are not yet tidy, since the
“route” variables are each their own column instead of being tidy under
one column.

  - How many distinct stations are there? Note that stations are
    identified both by name and by line (e.g. 125th St A/B/C/D; 125st 1;
    125st 4/5); the distinct function may be useful here.

<!-- end list -->

``` r
  filter(nyc_subway) %>%
  distinct(line, station_name) %>%
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   465

There are 465 distinct stations

  - How many stations are ADA compliant?

<!-- end list -->

``` r
  filter(nyc_subway, ada == TRUE) %>%
  distinct(line, station_name) %>%
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    84

84 trains are ADA compliant.

  - What proportion of station entrances / exits without vending allow
    entrance?

<!-- end list -->

``` r
nyc_entr= nyc_subway %>%
filter( vending == 'NO') %>%
  mutate(entrance_num = ifelse(entry == "TRUE", 1, 0)) %>%
  summarise(mean(entrance_num))
```

There are 37.704918 percent of entrance/exits without vending that allow
entrance.

  - Reformat data so that route number and route name are distinct
    variables.

<!-- end list -->

``` r
transit_tidy = nyc_subway %>%
  mutate_at(vars(route1:route11), as.character) %>%
  pivot_longer(
    route1:route11,
    names_to = "route_name",
    names_prefix = "route",
    values_to = "route_number") %>%
drop_na(route_number)
```

  - How many distinct stations serve the A train?

<!-- end list -->

``` r
filter(transit_tidy, route_number == "A") %>%
  distinct(station_name, line) %>%
count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    60

  - Of the stations that serve the A train, how many are ADA compliant?

<!-- end list -->

``` r
filter(transit_tidy, route_number == "A", ada == TRUE) %>%
  distinct(station_name, line) %>%
count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    17

60 distinct train stations serve the A train, and 17 of them are ADA
compliant.

-----

## Problem 3

First, clean the data in pols-month.csv. Use separate() to break up the
variable mon into integer variables year, month, and day; replace month
number with month name; create a president variable taking values gop
and dem, and remove prez\_dem and prez\_gop; and remove the day
variable.

``` r
pols =
  read_csv("./data/pols-month.csv") %>%
  janitor::clean_names() %>% 
  separate(mon, c("year", "month", "day")) %>%
  mutate (prez = ifelse(prez_gop == 1, "gop", "dem"),
          year = as.numeric(year), 
          month = replace(month, month == "01", "Jan"),
          month = replace(month, month == "02", "Feb"),
          month = replace(month, month == "03", "Mar"),
          month = replace(month, month == "04", "Apr"),
          month = replace(month, month == "05", "May"),
          month = replace(month, month == "06", "Jun"),
          month = replace(month, month == "07", "Jul"),
          month = replace(month, month == "08", "Aug"),
          month = replace(month, month == "09", "Sep"),
          month = replace(month, month == "10", "Oct"),
          month = replace(month, month == "11", "Nov"),
          month = replace(month, month == "12", "Dec")) %>% 
  select (-prez_gop, -prez_dem, -day)
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )

Second, clean the data in snp.csv using a similar process to the above.
For consistency across datasets, arrange according to year and month,
and organize so that year and month are the leading columns.

``` r
snp =
  read_csv("./data/snp.csv") %>%
  janitor::clean_names() %>% 
  separate(date, c("month", "day", "year")) %>% 
  mutate(year = as.numeric(year), 
          month = replace(month, month == "1", "Jan"),
          month = replace(month, month == "2", "Feb"),
          month = replace(month, month == "3", "Mar"),
          month = replace(month, month == "4", "Apr"),
          month = replace(month, month == "5", "May"),
          month = replace(month, month == "6", "Jun"),
          month = replace(month, month == "7", "Jul"),
          month = replace(month, month == "8", "Aug"),
          month = replace(month, month == "9", "Sep"),
          month = replace(month, month == "10", "Oct"),
          month = replace(month, month == "11", "Nov"),
          month = replace(month, month == "12", "Dec")) %>% 
  select (year, month, -day, close) %>% 
  arrange (year, month)
```

    ## Parsed with column specification:
    ## cols(
    ##   date = col_character(),
    ##   close = col_double()
    ## )

Third, tidy the unemployment data so that it can be merged with the
previous datasets. This process will involve switching from “wide” to
“long” format; ensuring that key variables have the same name; and
ensuring that key variables take the same values.

``` r
unemp=
  read_csv("./data/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec, 
    names_to = "month", 
    values_to = "rate")
```

    ## Parsed with column specification:
    ## cols(
    ##   Year = col_double(),
    ##   Jan = col_double(),
    ##   Feb = col_double(),
    ##   Mar = col_double(),
    ##   Apr = col_double(),
    ##   May = col_double(),
    ##   Jun = col_double(),
    ##   Jul = col_double(),
    ##   Aug = col_double(),
    ##   Sep = col_double(),
    ##   Oct = col_double(),
    ##   Nov = col_double(),
    ##   Dec = col_double()
    ## )

Now joining the datasets.

``` r
q2_merge =
  left_join(pols, snp, by =c("year","month"))
q2_merge
```

    ## # A tibble: 822 x 10
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem prez  close
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr> <dbl>
    ##  1  1947 Jan        23      51     253      23      45     198 dem      NA
    ##  2  1947 Feb        23      51     253      23      45     198 dem      NA
    ##  3  1947 Mar        23      51     253      23      45     198 dem      NA
    ##  4  1947 Apr        23      51     253      23      45     198 dem      NA
    ##  5  1947 May        23      51     253      23      45     198 dem      NA
    ##  6  1947 Jun        23      51     253      23      45     198 dem      NA
    ##  7  1947 Jul        23      51     253      23      45     198 dem      NA
    ##  8  1947 Aug        23      51     253      23      45     198 dem      NA
    ##  9  1947 Sep        23      51     253      23      45     198 dem      NA
    ## 10  1947 Oct        23      51     253      23      45     198 dem      NA
    ## # ... with 812 more rows

``` r
final_db = 
  left_join(q2_merge,unemp, by =c("year","month"))
```

These datasets provide information on who was in power by month starting
in the late 1940s and early 50s including `snp`, which provides data on
the S\&P 500, and unemployment data. The resulting database `final_db`
combines all these datasets to show variables such as number of senators
per party (`sen_dem` and `sen_gop`), the political party of the
president (`prez`) and `snp`, and unemployment data. The databases has
822 observations and covers January 1947 to June 2015.
